### ISSUE TITLE
Baraja

### ISSUE THREAD

**Issue by ioliasa** [sandra86code/Programacion2#1]
El método getSiguiente, ponle la anotación 	@Override para que si te confundes en los parámetros o en el valor devuelve te marque el error.

En el método getCartas devuelves el array completo de cartas, pero luego con lo usas en el toString llamas varias veces a la función, aunque sólo sacas una de las cartas cada vuelta del bucle, vuelves a pedir el array completo en la siguiente vuelta. O cambias esa función para que te devuelve sólo la carta que está en una determinada posición o sólo llamas una vez al método guardándolo en una variable.

**Comment by sandra86code** [comment]
Issue solucionado
